### PR TITLE
support batch entry append

### LINKED ISSUE #64: [RMQ-ISSUE-690][Feature] support Batch Entry Append
RocketMQ doesn't implement putMessages in DLedgerCommitLog.
It could be easier to implement putMessages with DLedger supporting Batch Entry Appending.

### PR DESCRIPTION
**Pull request by TerrellChen**
Fixed #64

### CODE REVIEW

**Comment by RongtongJin** [comment]
Hi @TerrellChen sorry to reply you so late. I want to ask if there is a corresponding rocketmq implementation for batch message ?

**Comment by RongtongJin** [comment]
IMO, this implementation is correct. We need to complete the implementation in RocketMQ and do some chaos tests to confirm that there is no problem. I am willing to follow this pr and help to merge it.

**Comment by TerrellChen** [comment]
Yes,  there is a corresponding rocketmq implementation for batch message. I will submit a pr for this.
But how to set the correct version for dledger in rocketmq's pom?

**Comment by TerrellChen** [comment]
Please check the mail when you are convenient. @RongtongJin

**Review by vongosling — APPROVED** [review]

**Comment by RongtongJin** [comment]
> Please check the mail when you are convenient. @RongtongJin

Good job! I have received your email and will review it ASAP. I will consider quickly releasing a minor version for DLedger to help you submit PR to rocketmq repo.

**Comment by RongtongJin** [comment]
@TerrellChen 
DLedger 0.2.1 has been released and contains the latest batch append code. So you can submit a pull request to RocketMQ repository.  I have reviewed your code and I think it is correct. But maybe the version you are based on is older, so you need to implement asyncPutMessages method and pay attention to the relevant modifications of IPv6, I don't think it's hard for you: -)

If you submit a PR, I'll track the PR and help to merge.

**Pull request merged**
